openapi: 3.0.0
info:
  title: carrier
  description: computer go beep boop
  version: 3.0.0

servers:
  - url: https://carrier.devguard.io/
    description: prod

components:
  schemas:
    IdentifyResponse:
      type: object
      properties:
        Identity:
          type: string
      required:
        - Identity
    RegistrationResponse:
      type: object
      properties:
        Identity:
          type: string
        Seat:
          type: integer
        Org:
          type: string
      required:
        - Identity
        - Seat
        - Org
    Connect:
      type: object
      properties:
        Caller:
          type: string
      required:
        - Caller

paths:


  /v1/identify:
    get:
      responses:
        '200':
          description: "ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/IdentifyResponse'
  /v1/register:
    post:
      parameters:
        - in: header
          name: X-AutoReg-Secret
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "ok"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegistrationResponse'
  /v1/listen:
    connect:
      responses:
        '101':
          description: "upgrade"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Connect'
